version: "3"

services:
  golang:
    build:
      context: .
    container_name: ${PROJECT_NAME}
    ports:
      - 8083:8083
    restart: always
    environment:
      - ENV = local
      - PROJECT_NAME = ${PROJECT_NAME}
    working_dir: /go/src/${PROJECT_NAME}
    depends_on:
      - mongo
    networks:
      - shorty_service
    volumes:
      - .:/go/src/${PROJECT_NAME}
    command: "fresh runner.conf"
  mongo:
    image: mongo
    container_name: ${PROJECT_NAME}-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /home/DB/${PROJECT_NAME}
    networks:
      - shorty_service
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ${PROJECT_NAME}-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    networks:
      - shorty_service

networks:
  shorty_service:
    external: true